apiVersion: v1
kind: Service
metadata:
  name: {{.Values.fullnameOverride}}
  labels:
    {{- include "chart-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart-app.selectorLabels" . | nindent 4 }}
{{- if .Values.tesseract-ui.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.tesseract-ui.fullnameOverride}}
  labels:
    {{- include "chart-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tesseract-ui.service.type }}
  ports:
    - port: {{ .Values.tesseract-ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart-app.selectorLabels" . | nindent 4 }}
{{- end }}
