{{- if .Values.tesseractUI.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.tesseractUI.fullnameOverride}}
  labels:
    {{- include "chart-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tesseractUI.service.type }}
  ports:
    - port: {{ .Values.tesseractUI.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart-app.selectorLabels" . | nindent 4 }}
{{- end }}