name: "Build Development into Artifact Registry"

# trigger the workflow when a push is committed to the develop branch
on:
  push:
    branches:
      - develop

jobs:
  # builds the docker image via cloud build
  build:
    name: Build Development Docker Image
    uses: ./.github/workflows/gcp-build-to-registry.yml
    with:
      IMAGE_NAME: healthycommunities-api
      IMAGE_TAG: ${{ github.sha }}
      IMAGE_ENVIRONMENT: dev
    secrets: inherit