name: "Build Development into Artifact Registry"

# trigger the workflow when a push is committed to the develop branch
on:
  push:
    branches:
      - develop

jobs:
  # builds the docker image via cloud build
  build:
    name: Build Docker Image into Artifact Registry
    uses: ./.github/workflows/gcp-build-to-registry.yml
    with:
      IMAGE_NAME: healthycommunities-api
      IMAGE_TAG: ${{ github.sha }}
      IMAGE_ENVIRONMENT: dev
    secrets: inherit

  # deploys the image to a cluster on gke
  deploy:
    name: Deploy Docker Image on GKE
    needs: build
    environment: develop_environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}

      - name: Restart Deployment
        run: kubectl rollout restart deployment/${{ secrets.GKE_DEPLOYMENT_NAME }}